"use strict";
const $=s=>document.querySelector(s);let setup=location.pathname==="/setup";
let themePref="system";try{themePref=localStorage.getItem("hch5-theme-preference")||"system"}catch(e){}const systemDark=matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.dataset.theme=themePref==="dark"?"dark":themePref==="light"?"light":systemDark?"dark":"light";
function setupView(){if(!setup){$("#confirm-row").style.display="none";return}$("#confirm-row").style.display="block";$("#auth-title").textContent="Opret første bruger";$("#auth-intro").textContent="Opret ejeren af HCH5 Control. Adgangskoden gemmes kun som et saltet hash på Raspberry Pi.";$("#password").autocomplete="new-password";$("#submit").textContent="Opret bruger"}
async function responseJson(response){try{return await response.json()}catch(_error){return {}}}
function networkMessage(){return "Kunne ikke kontakte HCH5 Control. Kontroller gateway-service."}
async function status(){try{const r=await fetch("/api/auth/status");const s=await responseJson(r);if(!r.ok)throw Error(s.error||"Kunne ikke hente login-status");setup=!s.configured;if(s.authenticated){location.replace("/");return}setupView()}catch(error){console.error("HCH5 Control auth status failed",error);$("#message").textContent=error instanceof TypeError?networkMessage():error.message}}
setupView();
$("#auth-form").addEventListener("submit",async e=>{e.preventDefault();const username=$("#username").value.trim(),password=$("#password").value,remember=$("#remember")?.checked===true;if(setup&&password!==$("#confirm").value){$("#message").textContent="Adgangskoderne er ikke ens";return}$("#submit").disabled=true;try{const r=await fetch(setup?"/api/auth/setup":"/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password,remember})});const p=await responseJson(r);if(!r.ok)throw Error(p.error||`Login mislykkedes (HTTP ${r.status})`);location.replace("/")}catch(error){console.error("HCH5 Control authentication failed",error);$("#message").textContent=error instanceof TypeError?networkMessage():error.message;$("#submit").disabled=false}});status();
