"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let authState={}, controllerState={}, liveState={};
const txt=(id,v)=>{const e=$(id);if(e)e.textContent=v==null||v===""?"—":String(v)};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v).toLocaleString("da-DK",{maximumFractionDigits:d}):"—";
const onoff=v=>v===true?"Ja":v===false?"Nej":"—";
function duration(v){v=Number(v);if(!Number.isFinite(v))return"—";const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60);return`${h}t ${m}m ${s}s`}
async function loadAuth(){try{const r=await fetch("/api/auth/status",{cache:"no-store"});authState=await r.json()}catch(e){authState={}}}
async function post(path,payload){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":authState.csrf||""},body:JSON.stringify(payload)});let data={};try{data=await r.json()}catch(e){}if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data}
function result(message,error=false){const el=$("#controller-result");if(!el)return;el.textContent=message;el.classList.toggle("controller-result-error",error);el.classList.toggle("controller-result-ok",!error)}
async function config(patch,message="Gemt"){try{controllerState=await post("/api/controller/config",patch);render();result(message)}catch(e){result(`Fejl: ${e.message}`,true)}}
function renderProfiles(){const body=$("#profile-body");if(!body)return;const profiles=controllerState.profiles||{};for(const level of [1,2,3,4,5,6]){const p=profiles[level]||profiles[String(level)]||{};let tr=body.querySelector(`tr[data-level="${level}"]`);if(!tr){tr=document.createElement("tr");tr.dataset.level=level;tr.innerHTML=`<td><b>${level}</b> <span data-profile-name></span></td><td><input data-profile="${level}" data-kind="extract" type="number" min="11" max="100"></td><td><input data-profile="${level}" data-kind="supply" type="number" min="10" max="99"></td><td data-diff="${level}">—</td>`;body.append(tr)}txt(`[data-level="${level}"] [data-profile-name]`,p.name||"");for(const kind of ["extract","supply"]){const input=tr.querySelector(`input[data-kind="${kind}"]`);if(input&&document.activeElement!==input&&String(input.value)!==String(p[kind]??""))input.value=p[kind]??""}const diff=Number.isFinite(Number(p.extract))&&Number.isFinite(Number(p.supply))?`${Number(p.extract)-Number(p.supply)}%`:"—";txt(`[data-diff="${level}"]`,diff)}}
function render(){const s=controllerState||{},m=s.measurements||{},profile=s.effective_profile||{},master=s.active_master||"unknown";$("#controller-dot")?.classList.toggle("online",master==="pi");txt("#controller-status",master==="pi"?"RASPBERRY PI MASTER":master==="hcp4"?"HCP4 MASTER":"AFVENTER SIKKER MASTER");txt("#source-badge",(s.effective_source||"—").replaceAll("_"," ").toUpperCase());txt("#effective-reason",s.effective_reason||"—");txt("#effective-source",(s.effective_source||"—").replaceAll("_"," "));txt("#effective-level",s.effective_level?`Niveau ${s.effective_level}`:"—");txt("#effective-pair",profile.extract!=null?`${profile.extract}% / ${profile.supply}%`:"—");txt("#ha-badge",s.ha_online?"HA ONLINE":"HA OFFLINE");txt("#ha-age",s.ha_age_seconds!=null?`${num(s.ha_age_seconds,0)} s`:"—");
  $$('[data-mode]').forEach(b=>b.classList.toggle("active",b.dataset.mode===s.mode));$$('[data-level]').forEach(b=>b.classList.toggle("active",Number(b.dataset.level)===Number(s.effective_level)));
  txt("#live-rh",m.rh??liveState.humidity);txt("#live-co2",m.co2??liveState.co2);txt("#auto-level-badge",s.effective_source?.startsWith("local")?`NIVEAU ${s.effective_level||"—"}`:"AUTO");
  const bind={"#rh-setpoint":s.rh_setpoint,"#rh-hysteresis":s.rh_hysteresis,"#co2-setpoint":s.co2_setpoint,"#co2-hysteresis":s.co2_hysteresis,"#normal-level":s.local_normal_level,"#downshift-delay":s.downshift_delay_seconds,"#boost-hold":s.boost_hold_seconds};for(const [id,v] of Object.entries(bind)){const e=$(id);if(e&&document.activeElement!==e)e.value=v??""}
  const fireplace=$("#fireplace-toggle");if(fireplace)fireplace.checked=!!s.fireplace;const sp=s.afterheat_setpoint;txt("#afterheat-display",sp??20);txt("#afterheat-active-badge",liveState.afterheat_active?"AKTIV":"INAKTIV");txt("#bypass-actual",onoff(liveState.bypass_active));txt("#fireplace-actual",onoff(liveState.fireplace));txt("#afterheat-actual",onoff(liveState.afterheat_active));txt("#last-write",s.last_write_at?new Date(Number(s.last_write_at)*1000).toLocaleTimeString("da-DK"):"—");txt("#write-failures",s.write_failures??0);txt("#last-error",s.last_error||"Ingen");txt("#controller-uptime",duration(s.controller_uptime_seconds));txt("#write-badge",s.last_error?"FEJL":s.hardware_writes_allowed?"SKRIVER":"AFVENTER");renderProfiles()}
async function poll(){try{const [c,l]=await Promise.all([fetch("/api/controller/state",{cache:"no-store"}),fetch("/state.json",{cache:"no-store"})]);if(!c.ok)throw Error(`Controller HTTP ${c.status}`);controllerState=await c.json();if(l.ok)liveState=await l.json();render()}catch(e){txt("#controller-status","FORBINDELSE TABT");result(`Fejl: ${e.message}`,true)}}
$$('[data-mode]').forEach(b=>b.addEventListener("click",()=>config({mode:b.dataset.mode},`Mode: ${b.textContent}`)));
$$('[data-level]').forEach(b=>b.addEventListener("click",()=>config({mode:"manual",manual_level:Number(b.dataset.level)},`Manuel niveau ${b.dataset.level}`)));
$("#save-auto")?.addEventListener("click",()=>config({rh_setpoint:Number($("#rh-setpoint").value),rh_hysteresis:Number($("#rh-hysteresis").value),co2_setpoint:Number($("#co2-setpoint").value),co2_hysteresis:Number($("#co2-hysteresis").value),local_normal_level:Number($("#normal-level").value),downshift_delay_seconds:Number($("#downshift-delay").value),boost_hold_seconds:Number($("#boost-hold").value)},"Local Auto gemt"));
$("#fireplace-toggle")?.addEventListener("change",e=>config({fireplace:e.target.checked},e.target.checked?"Pejsetilstand aktiveret":"Pejsetilstand deaktiveret"));
$$('[data-afterheat]').forEach(b=>b.addEventListener("click",()=>config({afterheat_setpoint:Number(b.dataset.afterheat)},`Eftervarme ${b.dataset.afterheat}°C`)));
$("#afterheat-minus")?.addEventListener("click",()=>{const current=controllerState.afterheat_setpoint??20;config({afterheat_setpoint:Math.max(18,Number(current)-1)})});
$("#afterheat-plus")?.addEventListener("click",()=>{const current=controllerState.afterheat_setpoint??20;config({afterheat_setpoint:Math.min(30,Number(current)+1)})});
$("#profile-body")?.addEventListener("input",e=>{if(!e.target.matches("input[data-profile]"))return;const level=e.target.dataset.profile,a=$(`input[data-profile="${level}"][data-kind="extract"]`),b=$(`input[data-profile="${level}"][data-kind="supply"]`),d=$(`[data-diff="${level}"]`);if(d)d.textContent=Number.isFinite(Number(a.value))&&Number.isFinite(Number(b.value))?`${Number(a.value)-Number(b.value)}%`:"—"});
$("#save-profiles")?.addEventListener("click",()=>{const profiles={};for(const level of [1,2,3,4,5,6])profiles[level]={extract:Number($(`input[data-profile="${level}"][data-kind="extract"]`).value),supply:Number($(`input[data-profile="${level}"][data-kind="supply"]`).value)};config({profiles},"Fanprofiler gemt")});
(async()=>{await loadAuth();await poll();setInterval(poll,2000)})();
