"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let authState={}, controllerState={}, liveState={}, afterheatDraft=null;
const txt=(id,v)=>{const e=$(id);if(e)e.textContent=v==null||v===""?"—":String(v)};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v).toLocaleString("da-DK",{maximumFractionDigits:d}):"—";
const onoff=v=>v===true?"Ja":v===false?"Nej":"—";
function duration(v){v=Number(v);if(!Number.isFinite(v))return"—";const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=Math.floor(v%60);return`${h}t ${m}m ${s}s`}
async function loadAuth(){try{const r=await fetch("/api/auth/status",{cache:"no-store"});authState=await r.json()}catch(e){authState={}}}
async function post(path,payload){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":authState.csrf||""},body:JSON.stringify(payload)});let data={};try{data=await r.json()}catch(e){}if(!r.ok)throw Error(data.error||`HTTP ${r.status}`);return data}
function result(message,error=false){const el=$("#controller-result");if(!el)return;el.textContent=message;el.classList.toggle("controller-result-error",error);el.classList.toggle("controller-result-ok",!error)}
async function config(patch,message="Gemt"){try{controllerState=await post("/api/controller/config",patch);render();result(message)}catch(e){result(`Fejl: ${e.message}`,true)}}
function renderProfiles(){const body=$("#profile-body");if(!body)return;const profiles=controllerState.profiles||{};body.replaceChildren(...[1,2,3,4,5,6].map(level=>{const p=profiles[level]||profiles[String(level)]||{};const tr=document.createElement("tr");tr.innerHTML=`<td><b>${level}</b> ${p.name||""}</td><td><input data-profile="${level}" data-kind="extract" type="number" min="11" max="100" value="${p.extract??""}"></td><td><input data-profile="${level}" data-kind="supply" type="number" min="10" max="99" value="${p.supply??""}"></td><td data-diff="${level}">${Number.isFinite(Number(p.extract))&&Number.isFinite(Number(p.supply))?Number(p.extract)-Number(p.supply):"—"}%</td>`;return tr}))}
function render(){const s=controllerState||{},m=s.measurements||{},profile=s.effective_profile||{};$("#controller-enabled").checked=!!s.enabled;$("#controller-dot").classList.toggle("online",!!s.enabled);txt("#controller-status",s.enabled?"CONTROLLER AKTIV":"CONTROLLER FRA");txt("#source-badge",(s.effective_source||"—").replaceAll("_"," ").toUpperCase());txt("#effective-reason",s.effective_reason||"—");txt("#effective-source",(s.effective_source||"—").replaceAll("_"," "));txt("#effective-level",s.effective_level?`Niveau ${s.effective_level}`:"—");txt("#effective-pair",profile.extract!=null?`${profile.extract}% / ${profile.supply}%`:"—");txt("#ha-badge",s.ha_online?"HA ONLINE":"HA OFFLINE");txt("#ha-age",s.ha_age_seconds!=null?`${num(s.ha_age_seconds,0)} s":"—`");if($("#ha-age"))$("#ha-age").textContent=s.ha_age_seconds!=null?`${num(s.ha_age_seconds,0)} s`:"—";
  $$('[data-mode]').forEach(b=>b.classList.toggle("active",b.dataset.mode===s.mode));$$('[data-level]').forEach(b=>b.classList.toggle("active",Number(b.dataset.level)===Number(s.effective_level)));
  txt("#live-rh",m.rh??liveState.humidity);txt("#live-co2",m.co2??liveState.co2);txt("#auto-level-badge",s.effective_source?.startsWith("local")?`NIVEAU ${s.effective_level||"—"}`:"AUTO");
  const bind={"#rh-setpoint":s.rh_setpoint,"#rh-hysteresis":s.rh_hysteresis,"#co2-setpoint":s.co2_setpoint,"#co2-hysteresis":s.co2_hysteresis,"#normal-level":s.local_normal_level,"#downshift-delay":s.downshift_delay_seconds,"#bypass-mode":s.bypass};for(const [id,v] of Object.entries(bind)){const e=$(id);if(e&&document.activeElement!==e)e.value=v??""}
  $("#fireplace-toggle").checked=!!s.fireplace;const sp=s.afterheat_setpoint;afterheatDraft=sp==null?afterheatDraft:sp;txt("#afterheat-display",sp==null?"AUTO":sp);txt("#afterheat-active-badge",liveState.afterheat_active?"AKTIV":"INAKTIV");txt("#bypass-actual",onoff(liveState.bypass_active));txt("#fireplace-actual",onoff(liveState.fireplace));txt("#afterheat-actual",onoff(liveState.afterheat_active));txt("#last-write",s.last_write_at?new Date(Number(s.last_write_at)*1000).toLocaleTimeString("da-DK"):"—");txt("#write-failures",s.write_failures??0);txt("#last-error",s.last_error||"Ingen");txt("#controller-uptime",duration(s.controller_uptime_seconds));txt("#write-badge",s.last_error?"FEJL":s.enabled?"KLAR":"FRA");renderProfiles()}
async function poll(){try{const [c,l]=await Promise.all([fetch("/api/controller/state",{cache:"no-store"}),fetch("/state.json",{cache:"no-store"})]);if(c.ok)controllerState=await c.json();if(l.ok)liveState=await l.json();render()}catch(e){txt("#controller-status","FORBINDELSE TABT")}}
$("#controller-enabled")?.addEventListener("change",e=>config({enabled:e.target.checked},e.target.checked?"Controller aktiveret":"Controller deaktiveret"));
$$('[data-mode]').forEach(b=>b.addEventListener("click",()=>config({mode:b.dataset.mode},`Mode: ${b.textContent}`)));
$$('[data-level]').forEach(b=>b.addEventListener("click",()=>config({mode:"manual",manual_level:Number(b.dataset.level)},`Manuel niveau ${b.dataset.level}`)));
$("#save-auto")?.addEventListener("click",()=>config({rh_setpoint:Number($("#rh-setpoint").value),rh_hysteresis:Number($("#rh-hysteresis").value),co2_setpoint:Number($("#co2-setpoint").value),co2_hysteresis:Number($("#co2-hysteresis").value),local_normal_level:Number($("#normal-level").value),downshift_delay_seconds:Number($("#downshift-delay").value)},"Local Auto gemt"));
$("#bypass-mode")?.addEventListener("change",e=>config({bypass:e.target.value},`Bypass: ${e.target.value}`));
$("#fireplace-toggle")?.addEventListener("change",e=>config({fireplace:e.target.checked},e.target.checked?"Pejsetilstand aktiveret":"Pejsetilstand deaktiveret"));
$$('[data-afterheat]').forEach(b=>b.addEventListener("click",()=>config({afterheat_setpoint:b.dataset.afterheat==="auto"?null:Number(b.dataset.afterheat)},b.dataset.afterheat==="auto"?"Eftervarme bevarer nuværende setpunkt":`Eftervarme ${b.dataset.afterheat}°C`)));
$("#afterheat-minus")?.addEventListener("click",()=>{const current=controllerState.afterheat_setpoint??22;config({afterheat_setpoint:Math.max(5,Number(current)-1)})});
$("#afterheat-plus")?.addEventListener("click",()=>{const current=controllerState.afterheat_setpoint??22;config({afterheat_setpoint:Math.min(40,Number(current)+1)})});
$("#profile-body")?.addEventListener("input",e=>{if(!e.target.matches("input[data-profile]"))return;const level=e.target.dataset.profile,a=$(`input[data-profile="${level}"][data-kind="extract"]`),b=$(`input[data-profile="${level}"][data-kind="supply"]`);const d=$(`[data-diff="${level}"]`);if(d)d.textContent=Number.isFinite(Number(a.value))&&Number.isFinite(Number(b.value))?`${Number(a.value)-Number(b.value)}%`:"—"});
$("#save-profiles")?.addEventListener("click",()=>{const profiles={};for(const level of [1,2,3,4,5,6])profiles[level]={extract:Number($(`input[data-profile="${level}"][data-kind="extract"]`).value),supply:Number($(`input[data-profile="${level}"][data-kind="supply"]`).value)};config({profiles},"Fanprofiler gemt")});
(async()=>{await loadAuth();await poll();setInterval(poll,2000)})();
