"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let state={}, controllerState={}, authState={}, historyRange="24h", historyTimer, waterSwapped=false;
try{waterSwapped=localStorage.getItem("dantherm-water-swap")==="1"}catch(e){}
let theme="dark";try{theme=localStorage.getItem("dantherm-theme")||((matchMedia("(prefers-color-scheme: light)").matches)?"light":"dark")}catch(e){}document.documentElement.dataset.theme=theme;
const boolText=v=>v===true?"Ja":v===false?"Nej":v??"—";
const display=v=>typeof v==="boolean"?boolText(v):v===null||v===undefined||v===""?"—":String(v).replaceAll("_"," ");
const number=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString("da-DK",{maximumFractionDigits:d}):"—";
const color=t=>!Number.isFinite(Number(t))?"#718391":t<5?"#488ce0":t<14?"#54aaf4":t<19?"#49c8cf":t<23?"#e6ac56":"#ed7868";
function patchText(el,text){if(el&&el.textContent!==text)el.textContent=text}
function patchAttr(el,name,value){if(el&&el.getAttribute(name)!==value)el.setAttribute(name,value)}
function setIcon(id,status,spinning=false){const el=$(id);if(!el)return;el.classList.remove("good","active","warn","bad","spinning");if(status)el.classList.add(status);if(spinning)el.classList.add("spinning")}
const normalRoutes={outdoor:"M35 285 H300 Q330 285 350 265 L390 225",exhaust:"M390 195 L350 155 Q330 135 300 135 H35",extract:"M858 135 H600 Q570 135 550 155 L510 195",supply:"M510 225 L550 265 Q570 285 600 285 H858",supplyFlow:"M35 285 H300 Q330 285 350 265 L390 225 M510 225 L550 265 Q570 285 600 285 H858",extractFlow:"M858 135 H600 Q570 135 550 155 L510 195 M390 195 L350 155 Q330 135 300 135 H35"};
const bypassRoutes={outdoor:"M35 285 H450",supply:"M450 285 H858",extract:"M858 135 H450",exhaust:"M450 135 H35",supplyFlow:"M35 285 H858",extractFlow:"M858 135 H35"};
function updateAirRoutes(bypass){const r=bypass?bypassRoutes:normalRoutes;for(const key of ["outdoor","exhaust","extract","supply"]){patchAttr($(`#${key}-base-path`),"d",r[key]);patchAttr($(`#${key}-temp-path`),"d",r[key])}patchAttr($("#supply-flow"),"d",r.supplyFlow);patchAttr($("#extract-flow"),"d",r.extractFlow);patchText($("#right-top-label"),"UDSUGNING");patchText($("#right-bottom-label"),"INDBLÆSNING");patchText($("#right-top-value"),`${number(state.extract_temp)}°`);patchText($("#right-bottom-value"),`${number(state.supply_temp)}°`);patchAttr($("#coil"),"transform","translate(715 285)")}
function updateWater(){const flowKey=waterSwapped?"return_temperature":"flow_temperature",returnKey=waterSwapped?"flow_temperature":"return_temperature",flowSensor=waterSwapped?"return_sensor":"flow_sensor",returnSensor=waterSwapped?"flow_sensor":"return_sensor";const f=Number(state[flowKey]),r=Number(state[returnKey]),delta=Number.isFinite(f)&&Number.isFinite(r)?f-r:NaN;patchText($('[data-water-temperature="flow"]'),number(f));patchText($('[data-water-temperature="return"]'),number(r));patchText($('[data-water-sensor="flow"]'),display(state[flowSensor]));patchText($('[data-water-sensor="return"]'),display(state[returnSensor]));patchText($("#water-delta"),Number.isFinite(delta)?`${number(delta)} K`:"—");patchText($("#flow-warning"),Number.isFinite(delta)&&delta<0?"Retur måles højere end fremløb. Du kan bytte visningen under Indstillinger.":"");patchText($("#swap-water-status"),waterSwapped?"Ombyttet visning aktiv":"Standard rækkefølge")}
function setState(next){state=next||{};$$('[data-value]').forEach(el=>patchText(el,display(state[el.dataset.value])));$$('[data-number]').forEach(el=>patchText(el,number(state[el.dataset.number])+(el.dataset.suffix||"")));const online=state.available===true&&state.bus_traffic===true;$("#online-dot").classList.toggle("online",online);patchText($("#online-label"),online?"FORBUNDET":"AFBRUDT");patchText($("#mode-badge"),online?`HCH5 · ${display(state.mode).toUpperCase()}`:"HCH5");patchText($("#snapshot-status"),state.bus_last_frame_age<=5?"OK":"STALE");const one=state.preheater_diagnostics_reachable===true&&state.flow_temperature!=null&&state.return_temperature!=null;patchText($("#onewire-status"),one?"OK":"FEJL");patchText($("#onewire-detail"),one?"ONLINE":"FEJL");
  const sr=Number(state.fan_supply_rpm)||0,er=Number(state.fan_extract_rpm)||0;$(".supply-fan").classList.toggle("running",sr>0);$(".extract-fan").classList.toggle("running",er>0);$("#supply-flow").classList.toggle("stopped",sr<=0);$("#extract-flow").classList.toggle("stopped",er<=0);$("#supply-flow").style.animationDuration=`${Math.max(2.4,6-sr/900)}s`;$("#extract-flow").style.animationDuration=`${Math.max(2.4,6-er/900)}s`;setIcon("#ventilation-icon",sr>0||er>0?"active":null,sr>0||er>0);patchText($('[data-fan="supply"]'),`${number(sr,0)} RPM · ${number(state.fan_supply_percent,0)}%`);patchText($('[data-fan="extract"]'),`${number(er,0)} RPM · ${number(state.fan_extract_percent,0)}%`);$("#outdoor-temp-path").style.stroke=color(state.outdoor_temp);$("#supply-temp-path").style.stroke=color(state.supply_temp);$("#extract-temp-path").style.stroke=color(state.extract_temp);$("#exhaust-temp-path").style.stroke=color(state.exhaust_temp);const bypass=state.bypass_active===true;$(".airflow").classList.toggle("bypass-open",bypass);updateAirRoutes(bypass);patchText($("#bypass-label"),bypass?"BYPASS ÅBEN":"BYPASS LUKKET");const heating=state.afterheat_active===true||Number(state.heating_valve_percent)>0;$("#coil").classList.toggle("active",heating);patchText($("#afterheat-badge"),heating?"AKTIV":"INAKTIV");
  const co2=Number(state.co2);patchText($("#co2-status"),!Number.isFinite(co2)?"Ukendt":co2<800?"God":co2<1200?"Moderat":"Høj");setIcon("#co2-icon",!Number.isFinite(co2)?null:co2<800?"good":co2<1200?"warn":"bad");const filter=Math.max(0,Math.min(100,Number(state.filter_life_percent)||0));$("#filter-meter").style.width=`${filter}%`;setIcon("#filter-icon",filter>40?"good":filter>15?"warn":"bad");
  const o=Number(state.outdoor_temp),x=Number(state.extract_temp),e=Number(state.exhaust_temp),den=x-o;const calculated=Number.isFinite(o)&&Number.isFinite(x)&&Number.isFinite(e)&&Math.abs(den)>=0.5?((x-e)/den)*100:NaN;const recoveryValid=!state.bypass_active&&Number.isFinite(calculated)&&calculated>=0&&calculated<=105;const rec=recoveryValid?`${number(calculated,0)}%`:"Ikke tilgængelig";setIcon("#recovery-icon",recoveryValid?"good":bypass?"active":"warn");patchText($("#recovery-value"),rec);patchText($("#recovery-card"),rec);const reason=state.bypass_active?"Bypass er åben; varmegenvindingen er koblet udenom.":Math.abs(den)<0.5?"Temperaturspændet er for lille til en stabil beregning.":"Udsugning eller afkast mangler en gyldig temperatur.";patchText($("#recovery-note"),recoveryValid?"Beregnet på udsugning → afkast, så varmefladen ikke forvrænger resultatet.":reason);patchText($("#recovery-card-note"),recoveryValid?"Beregnet på udsugning og afkast":reason);
  updateWater();patchText($("#pi-uptime"),duration(state.pi_uptime_seconds));renderPi();renderRaw();patchText($("#last-update"),`Opdateret ${new Date().toLocaleTimeString("da-DK")}`);
}
function renderController(){const s=controllerState||{},enabled=$("#overview-controller-enabled");if(enabled)enabled.checked=!!s.enabled;patchText($("#control-reason"),s.enabled?(s.effective_reason||"Controller aktiv"):"Controller er slået fra — ændringer gemmes uden RS485-writes");$$('[data-control-mode]').forEach(button=>button.classList.toggle("active",button.dataset.controlMode===s.mode));$$('[data-control-level]').forEach(button=>button.classList.toggle("active",Number(button.dataset.controlLevel)===Number(s.manual_level)));const afterheat=Number(s.afterheat_setpoint);patchText($("#overview-afterheat"),Number.isFinite(afterheat)?`${afterheat}°`:"20°");const bypass=$("#overview-bypass");if(bypass&&document.activeElement!==bypass)bypass.value=s.bypass||"auto";const fireplace=$("#overview-fireplace");if(fireplace)fireplace.checked=!!s.fireplace;patchText($("#overview-bypass-actual"),state.bypass_active===true?"Åben":state.bypass_active===false?"Lukket":"—");patchText($("#overview-fireplace-actual"),state.fireplace===true?"Til":state.fireplace===false?"Fra":"—")}
async function postController(patch,message){const result=$("#control-result");patchText(result,"Gemmer…");try{const response=await fetch("/api/controller/config",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":authState.csrf||""},body:JSON.stringify(patch)});const payload=await response.json();if(!response.ok)throw Error(payload.error||response.status);controllerState=payload;renderController();patchText(result,payload.enabled?message:`${message} — controller er slået fra`)}catch(error){patchText(result,`Fejl: ${error.message}`)}}
function duration(v){v=Number(v);if(!Number.isFinite(v))return"—";const d=Math.floor(v/86400),h=Math.floor(v%86400/3600),m=Math.floor(v%3600/60);return`${d?d+"d ":""}${h}t ${m}m`}
function renderPi(){const flags=[["Strøm",state.pi_undervoltage_now],["Throttling",state.pi_throttled_now],["Frekvens",state.pi_frequency_capped_now],["Temperatur",state.pi_soft_temp_limit_now]];const known=flags.every(([,v])=>typeof v==="boolean"),bad=flags.some(([,v])=>v===true);patchText($("#pi-health"),bad?"ADVARSEL":known?"HEALTHY":"DELVIS DATA");$("#pi-flags").replaceChildren(...flags.map(([n,v])=>{const e=document.createElement("span");e.className=v===true?"bad":"";e.textContent=`${n}: ${v===true?"FEJL":v===false?"OK":"UKENDT"}`;return e}))}
function renderRaw(){const q=$("#raw-search").value.toLowerCase();const rows=Object.entries(state).sort(([a],[b])=>a.localeCompare(b)).filter(([k,v])=>`${k} ${v}`.toLowerCase().includes(q));$("#raw-table").replaceChildren(...rows.map(([k,v])=>{const tr=document.createElement("tr"),a=document.createElement("td"),b=document.createElement("td");a.textContent=k.replaceAll("_"," ");b.textContent=display(v);tr.append(a,b);return tr}))}
async function poll(){try{const [stateResponse,controllerResponse]=await Promise.all([fetch("/state.json",{cache:"no-store"}),fetch("/api/controller/state",{cache:"no-store"})]);if(!stateResponse.ok)throw Error(stateResponse.status);setState(await stateResponse.json());if(controllerResponse.ok){controllerState=await controllerResponse.json();renderController()}}catch(e){$("#online-dot").classList.remove("online");patchText($("#online-label"),"FORBINDELSE TABT")}}
const chartDefs={temperatures:["Temperaturer",["outdoor_temp","supply_temp","extract_temp","exhaust_temp","hrc2_t5_temperature"]],afterheat:["Eftervarme",["flow_temperature","return_temperature","heating_valve_percent"]],air:["Luftkvalitet",["co2"]],fans:["Ventilatorer",["fan_supply_rpm","fan_extract_rpm","fan_supply_percent","fan_extract_percent"]],recovery:["Varmegenvinding",["heat_recovery_efficiency"]]};
function chartCard(key,title){const a=document.createElement("article");a.className="chart-card card";a.innerHTML=`<header><div><small>${key.toUpperCase()}</small><h2>${title}</h2></div></header><div class="chart-empty">Historik indlæses…</div>`;return a}
async function loadHistory(){clearTimeout(historyTimer);const grid=$("#chart-grid");if(!grid.children.length)Object.entries(chartDefs).forEach(([k,[t]])=>grid.append(chartCard(k,t)));try{const res=await fetch(`/history.json?range=${historyRange}`,{cache:"no-store"});if(!res.ok)throw Error();const payload=await res.json();Object.entries(chartDefs).forEach(([k,[,series]],i)=>drawChart(grid.children[i],payload,series,k==="recovery"))}catch(e){$$('.chart-empty',grid).forEach(x=>patchText(x,"Historik-endpoint er endnu ikke tilgængeligt"))}historyTimer=setTimeout(loadHistory,30000)}
function drawChart(card,payload,series,validRecovery){const rows=payload.samples||[],values=rows.flatMap(r=>series.map(k=>Number(r[k])).filter(v=>Number.isFinite(v)&&(!validRecovery||v<=100&&v>=0)));if(!values.length)return;const lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1,colors=["#54aaf4","#f0b45c","#49d2ba","#aa83ef","#ec7080"];const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 600 220");svg.classList.add("chart");for(let y=20;y<=200;y+=45){const l=document.createElementNS(svg.namespaceURI,"line");l.setAttribute("class","grid");l.setAttribute("x1","0");l.setAttribute("x2","600");l.setAttribute("y1",y);l.setAttribute("y2",y);svg.append(l)}series.forEach((k,n)=>{const pts=rows.map((r,i)=>[i,Number(r[k])]).filter(([,v])=>Number.isFinite(v)&&(!validRecovery||v<=100&&v>=0));if(pts.length<2)return;const p=document.createElementNS(svg.namespaceURI,"polyline");p.setAttribute("stroke",colors[n%colors.length]);p.setAttribute("points",pts.map(([i,v])=>`${i/(rows.length-1)*600},${200-(v-lo)/span*170}`).join(" "));svg.append(p)});card.querySelector(".chart-empty")?.replaceWith(svg)}
async function runAdmin(button){const action=button.dataset.adminAction,target=button.dataset.adminTarget||null;const labels={reboot:"genstarte Raspberry Pi",shutdown:"lukke Raspberry Pi helt ned",restart_service:`genstarte ${target}`,power_profile:`skifte CPU-profil til ${button.textContent}`};if(!confirm(`Vil du ${labels[action]}?`))return;const result=$("#admin-result");button.disabled=true;patchText(result,"Handlingen udføres…");try{const response=await fetch("/api/admin/action",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":authState.csrf||""},body:JSON.stringify({action,target})});const payload=await response.json();if(!response.ok)throw Error(payload.error||response.status);patchText(result,action==="shutdown"?"Pi'en lukker ned og skal tændes fysisk igen.":action==="reboot"?"Pi'en genstarter. Siden forsøger automatisk at forbinde igen.":"Handlingen er gennemført.")}catch(error){patchText(result,`Fejl: ${error.message}`)}finally{button.disabled=false}}
$$('[data-admin-action]').forEach(button=>button.addEventListener("click",()=>runAdmin(button)));
$("#download-debug").addEventListener("click",async()=>{const button=$("#download-debug"),result=$("#debug-result");button.disabled=true;patchText(result,"Rapporten samles…");try{const response=await fetch("/api/diagnostics/report",{cache:"no-store"});if(!response.ok)throw Error(response.status===503?"Diagnostik-helperen svarer ikke":`HTTP ${response.status}`);const blob=await response.blob();const disposition=response.headers.get("Content-Disposition")||"";const match=disposition.match(/filename="([^"]+)"/);const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=match?match[1]:"dantherm-debug.txt";document.body.append(link);link.click();const objectUrl=link.href;link.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);patchText(result,"Debugrapporten er hentet. Gennemse den før deling.")}catch(error){patchText(result,`Kunne ikke hente rapport: ${error.message}`)}finally{button.disabled=false}});
async function loadAuth(){const response=await fetch("/api/auth/status",{cache:"no-store"});authState=await response.json();$("#new-username").value=authState.username||"";$("#login-enabled").checked=authState.enabled!==false}
$("#login-enabled").addEventListener("change",()=>{$("#security-warning").hidden=$("#login-enabled").checked;if($("#login-enabled").checked)$("#risk-confirm").checked=false});
$("#auth-settings-form").addEventListener("submit",async event=>{event.preventDefault();const enabled=$("#login-enabled").checked;if(!enabled&&!$("#risk-confirm").checked){patchText($("#auth-settings-result"),"Du skal bekræfte, at du forstår sikkerhedsrisikoen.");return}const payload={username:$("#new-username").value.trim(),password:$("#new-password").value,current_password:$("#current-password").value,enabled};try{const response=await fetch("/api/auth/settings",{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":authState.csrf||""},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw Error(result.error||response.status);alert(enabled?"Loginoplysningerne er gemt. Log ind igen.":"Login er slået fra. Alle på lokalnettet har nu adgang.");location.replace(enabled?"/login":"/")}catch(error){patchText($("#auth-settings-result"),error.message)}});
$("#logout").addEventListener("click",async()=>{await fetch("/api/auth/logout",{method:"POST",headers:{"X-CSRF-Token":authState.csrf||""}});location.replace("/login")});
loadAuth();
$("#overview-controller-enabled")?.addEventListener("change",event=>postController({enabled:event.target.checked},event.target.checked?"Controller aktiveret":"Controller deaktiveret"));
$$('[data-control-mode]').forEach(button=>button.addEventListener("click",()=>postController({mode:button.dataset.controlMode},`Drift ændret til ${button.textContent}`)));
$$('[data-control-level]').forEach(button=>button.addEventListener("click",()=>postController({mode:"manual",manual_level:Number(button.dataset.controlLevel)},`Ventilation sat til niveau ${button.dataset.controlLevel}`)));
$("#overview-afterheat-minus")?.addEventListener("click",()=>postController({afterheat_setpoint:Math.max(18,Number(controllerState.afterheat_setpoint??20)-1)},"Eftervarme sænket"));
$("#overview-afterheat-plus")?.addEventListener("click",()=>postController({afterheat_setpoint:Math.min(30,Number(controllerState.afterheat_setpoint??20)+1)},"Eftervarme hævet"));
$("#overview-bypass")?.addEventListener("change",event=>postController({bypass:event.target.value},`Bypass: ${event.target.options[event.target.selectedIndex].text}`));
$("#overview-fireplace")?.addEventListener("change",event=>postController({fireplace:event.target.checked},event.target.checked?"Pejsetilstand aktiveret":"Pejsetilstand deaktiveret"));
function applyTheme(next){theme=next;document.documentElement.dataset.theme=theme;patchText($("#theme-toggle"),theme==="dark"?"☀":"☾");try{localStorage.setItem("dantherm-theme",theme)}catch(e){}}
$$('.tabs button').forEach(b=>b.addEventListener("click",()=>{$$('.tabs button').forEach(x=>x.classList.toggle("active",x===b));$$('.page').forEach(x=>x.classList.toggle("active",x.id===b.dataset.tab));if(b.dataset.tab==="history")loadHistory()}));$$('.ranges button').forEach(b=>b.addEventListener("click",()=>{historyRange=b.dataset.range;$$('.ranges button').forEach(x=>x.classList.toggle("active",x===b));loadHistory()}));$("#raw-search").addEventListener("input",renderRaw);$("#swap-water").addEventListener("click",()=>{waterSwapped=!waterSwapped;try{localStorage.setItem("dantherm-water-swap",waterSwapped?"1":"0")}catch(e){}updateWater()});$("#theme-toggle").addEventListener("click",()=>applyTheme(theme==="dark"?"light":"dark"));applyTheme(theme);poll();setInterval(poll,3000);
