"use strict";
let csrf="",snifferRunning=false;
async function authStatus(){try{const r=await fetch('/api/auth/status',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();csrf=j.csrf||'';return j}catch(e){return{authenticated:false}}}
async function api(path,opts={}){opts.headers=opts.headers||{};if(csrf)opts.headers['X-CSRF-Token']=csrf;opts.credentials='same-origin';const r=await fetch(path,opts);if(r.status===401)throw new Error('Ikke logget ind');const j=await r.json().catch(()=>null);if(!r.ok)throw new Error((j&&j.error)||`HTTP ${r.status}`);return j}
function setStatus(s){snifferRunning=!!s.running;const status=document.getElementById('status'),counts=document.getElementById('counts'),badge=document.getElementById('sniffer-badge'),start=document.getElementById('start'),stop=document.getElementById('stop');status.textContent=`${s.running?'Kører':'Stoppet'}${s.connected?' · RS485 forbundet':''}`;counts.textContent=`${s.frames||0} frames · ${s.bytes||0} bytes`;if(badge){badge.textContent=s.running?'CAPTURE AKTIV':'STOPPET';badge.classList.toggle('safe',!!s.running)}if(start)start.disabled=!!s.running;if(stop)stop.disabled=!s.running}
async function refresh(){try{const [s,recent]=await Promise.all([api('/api/sniffer/status'),api('/api/sniffer/recent')]);setStatus(s);const lines=(recent||[]).slice(-60).map(r=>{const dir=r.direction||'?';const slave=r.slave!=null?`0x${Number(r.slave).toString(16).padStart(2,'0')}`:'--';const fn=r.function!=null?`FC${String(r.function).padStart(2,'0')}`:'--';const detail=r.register!=null?`R${r.register}=${r.value}`:r.start_register!=null?`R${r.start_register} × ${r.count}`:'';return `${r.wall_clock||''}  ${dir.padEnd(10)} ${slave} ${fn} ${detail}  ${r.raw_hex||''}`.trim()});document.getElementById('recent').textContent=lines.join('\n')||'(ingen frames endnu)'}catch(e){document.getElementById('recent').textContent=`Fejl: ${e.message}`}}
async function start(){try{await api('/api/sniffer/start',{method:'POST'});await refresh()}catch(e){document.getElementById('recent').textContent=`Kunne ikke starte capture: ${e.message}`}}
async function stop(){try{await api('/api/sniffer/stop',{method:'POST'});await refresh()}catch(e){document.getElementById('recent').textContent=`Kunne ikke stoppe capture: ${e.message}`}}
async function marker(name){try{await api('/api/sniffer/marker',{method:'POST',body:JSON.stringify({name}),headers:{'Content-Type':'application/json'}});const input=document.getElementById('manual-label');if(input&&input.value.trim()===name)input.value='';await refresh()}catch(e){document.getElementById('recent').textContent=`Kunne ikke oprette markør: ${e.message}`}}
function makeButtons(){const names=["HCP4_CONNECTED","BYPASS_AUTO_A","BYPASS_OPEN","BYPASS_AUTO_B","BYPASS_CLOSED","BYPASS_AUTO_C","T3_OFF_A","T3_16","T3_21","T3_27","T3_30","T3_OFF_B","T5_OFF_A","T5_16","T5_21","T5_27","T5_30","T5_OFF_B","T3_20_T5_OFF","T3_OFF_T5_24","T3_OFF_T5_OFF","HCP4_DISCONNECTED"];const el=document.getElementById('marker-buttons');for(const n of names){const b=document.createElement('button');b.type='button';b.textContent=n;b.addEventListener('click',()=>marker(n));el.appendChild(b)}}
window.addEventListener('load',async()=>{const auth=await authStatus();if(!auth.authenticated&&auth.enabled){location.href='/login';return}makeButtons();document.getElementById('start').addEventListener('click',start);document.getElementById('stop').addEventListener('click',stop);document.getElementById('manual-marker').addEventListener('click',()=>{const v=document.getElementById('manual-label').value.trim();if(v)marker(v)});document.getElementById('manual-label').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const v=e.target.value.trim();if(v)marker(v)}});setInterval(refresh,1500);refresh()});
