import { useCallback, useEffect, useState } from "react";
import { Activity, Download, RefreshCw, Server, ShieldAlert, Wrench } from "lucide-react";
import { InfoList } from "../components/InfoList";
import { postJson, requestJson } from "../lib/api";
import "../styles/panels.css";import "../styles/management.css";
type Data=Record<string,unknown>;type Auth={csrf?:string|null};
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:null}function age(v:unknown){const n=num(v);return n===null?"—":`${n.toLocaleString("da-DK",{maximumFractionDigits:1})} sek`}
export function DiagnosticsPage(){const[state,setState]=useState<Data>({});const[controller,setController]=useState<Data>({});const[csrf,setCsrf]=useState("");const[selfTest,setSelfTest]=useState<string[]>([]);const[busy,setBusy]=useState(false);const refresh=useCallback(async()=>{const[a,b,c]=await Promise.allSettled([requestJson<Data>("/state.json",{timeoutMs:4000}),requestJson<Data>("/api/controller/state",{timeoutMs:4000}),requestJson<Auth>("/api/auth/status",{timeoutMs:4000})]);if(a.status==="fulfilled")setState(a.value);if(b.status==="fulfilled")setController(b.value);if(c.status==="fulfilled")setCsrf(c.value.csrf??"")},[]);useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),5000);return()=>clearInterval(t)},[refresh]);
 const runTest=async()=>{setBusy(true);const[a,b,c]=await Promise.allSettled([requestJson<Data>("/state.json"),requestJson<Data>("/api/controller/state"),requestJson<Auth>("/api/auth/status")]);const lines=[`WebUI/API: ${a.status==="fulfilled"?"PASS":"FAIL"}`,`Controller runtime: ${b.status==="fulfilled"?"PASS":"FAIL"}`,`Auth: ${c.status==="fulfilled"?"PASS":"FAIL"}`,`RS485: ${b.status==="fulfilled"&&b.value.rs485_healthy===true?"PASS":"CHECK"}`,`Raw mirror: ${state.bus_traffic===true?"PASS (bus data active)":"CHECK"}`,`Gateway service: ${state.service_gateway_activestate==="active"?"PASS":"CHECK"}`,`Admin service: ${state.service_admin_activestate==="active"||state.admin_service_activestate==="active"?"PASS":"CHECK"}`];setSelfTest(lines);setBusy(false)};
 const restart=async()=>{if(!csrf||!window.confirm("Genstart gateway-servicen? Ventilationens lokale sikkerhedslogik bevares, men WebUI kan være væk kortvarigt."))return;await postJson("/api/admin/action",{action:"restart_service",target:"gateway"},csrf);};
 return <section className="dashboard-overview page-enter"><header className="overview-heading-row"><div><span className="eyebrow">DIAGNOSTIK</span><h1>Fejlsøgning og helbred</h1><p>Read-only status for controller, RS485, sensorer og services.</p></div><div className="overview-status-pills"><div><span className={`status-led ${controller.rs485_healthy===true?"":"warn"}`}/><small>RS485</small><strong>{controller.rs485_healthy===true?"Healthy":"Check"}</strong></div><div><ShieldAlert size={18}/><small>Write gate</small><strong>{controller.hardware_writes_allowed===true?"Allowed":"Blocked"}</strong></div></div></header>
 <div className="panel-grid"><article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Master arbitration</h2><p>HCP4 vinder altid</p></div><Activity size={20}/></div><InfoList rows={[{label:"Active master",value:text(controller.active_master)},{label:"Hardware writes",value:controller.hardware_writes_allowed===true?"Allowed":"Blocked",tone:controller.hardware_writes_allowed===true?"ok":"neutral"},{label:"Control state",value:text(controller.hardware_control_state)},{label:"Bus age",value:age(controller.bus_last_frame_age??state.bus_last_frame_age)},{label:"Effective source",value:text(controller.effective_source)},{label:"Reason",value:text(controller.effective_reason)}]}/></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>RS485 / data</h2><p>19200 · 8E1</p></div><Wrench size={20}/></div><InfoList rows={[{label:"Bus healthy",value:controller.rs485_healthy===true?"Ja":"Nej",tone:controller.rs485_healthy===true?"ok":"warn"},{label:"Traffic",value:state.bus_traffic===true?"Aktiv":"Afventer"},{label:"Frame rate",value:text(state.bus_frame_rate)},{label:"T2 source",value:text(controller.actual_supply_before_heater_temperature_source)},{label:"T2 age",value:age(controller.actual_supply_before_heater_age_seconds)},{label:"Last controller error",value:text(controller.last_error,"Ingen"),tone:controller.last_error?"bad":"ok"}]}/></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Services</h2><p>Systemd og porte</p></div><Server size={20}/></div><InfoList rows={[{label:"Gateway",value:text(state.service_gateway_activestate),tone:state.service_gateway_activestate==="active"?"ok":"warn"},{label:"Admin",value:text(state.service_admin_activestate??state.admin_service_activestate)},{label:"1-Wire",value:text(state.service_onewire_activestate)},{label:"Gateway PID",value:text(state.service_gateway_mainpid??state.service_gateway_pid)},{label:"8080",value:"WebUI/API"},{label:"4196",value:"Read-only RS485 mirror"}]}/></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Sikker systemtest</h2><p>Kun reads — ingen Modbus writes</p></div><RefreshCw size={20}/></div><div className="diag-actions"><button className="primary-action" disabled={busy} onClick={()=>void runTest()}>{busy?"Tester…":"Kør systemtest"}</button><a className="secondary-action" href="/api/diagnostics/report"><Download size={15}/> Download rapport</a><button className="danger-outline" onClick={()=>void restart()}>Genstart gateway</button></div>{selfTest.length>0&&<pre className="self-test-output">{selfTest.join("\n")}</pre>}</article></div></section>}
