import { useCallback, useEffect, useState } from "react";
import { Activity, Home, Radio, ShieldCheck, Wifi } from "lucide-react";
import { InfoList } from "../components/InfoList";
import { requestJson } from "../lib/api";
import "../styles/panels.css";
import "../styles/management.css";
type Data=Record<string,unknown>;
function text(v:unknown,f="—"){return v===null||v===undefined||v===""?f:String(v)}
function age(v:unknown){const n=Number(v);return Number.isFinite(n)?`${n.toLocaleString("da-DK",{maximumFractionDigits:1})} sek`:"—"}
function bool(v:unknown){return v===true?"Ja":v===false?"Nej":"—"}
export function HomeAssistantPage(){const[state,setState]=useState<Data>({});const[controller,setController]=useState<Data>({});const[online,setOnline]=useState(false);
 const refresh=useCallback(async()=>{const[a,b]=await Promise.allSettled([requestJson<Data>("/state.json",{timeoutMs:3500}),requestJson<Data>("/api/controller/state",{timeoutMs:3500})]);if(a.status==="fulfilled")setState(a.value);if(b.status==="fulfilled")setController(b.value);setOnline(a.status==="fulfilled"&&b.status==="fulfilled")},[]);
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),5000);return()=>clearInterval(t)},[refresh]);
 const rooms=(controller.smart_ha_rooms&&typeof controller.smart_ha_rooms==="object"?controller.smart_ha_rooms:{}) as Record<string,Data>;const roomEntries=Object.entries(rooms);const smartFresh=controller.smart_inputs_online===true;const master=text(controller.active_master).toLowerCase();
 return <section className="dashboard-overview page-enter"><header className="overview-heading-row"><div><span className="eyebrow">HOME ASSISTANT</span><h1>Integration og smart-data</h1><p>HA er klient. HCH5 Control fortsætter lokalt, også når Home Assistant er offline.</p></div><div className="overview-status-pills"><div><span className={`status-led ${online?"":"warn"}`}/><small>Integration</small><strong>{online?"Forbundet":"Afventer"}</strong></div><div><Radio size={18}/><small>Smart inputs</small><strong>{smartFresh?"Friske":"Stale / mangler"}</strong></div><div><ShieldCheck size={18}/><small>Master</small><strong>{master==="pi"?"Raspberry Pi":master==="hcp4"?"HCP4":"Unknown"}</strong></div></div></header>
 <div className="panel-grid"><article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Forbindelse</h2><p>Controller API og leased HA-inputs</p></div><Wifi size={20}/></div><InfoList rows={[{label:"Controller API",value:online?"Online":"Offline",tone:online?"ok":"bad"},{label:"Integration domain",value:"hch_passivelink"},{label:"Sidst input",value:age(controller.smart_inputs_age_seconds),tone:smartFresh?"ok":"warn"},{label:"Lease",value:controller.smart_inputs_valid_for_seconds?`${text(controller.smart_inputs_valid_for_seconds)} sek`:"—"},{label:"Aktive HA-rum",value:String(roomEntries.length)},{label:"Hardware writes",value:controller.hardware_writes_allowed===true?"Allowed":"Blocked",tone:controller.hardware_writes_allowed===true?"ok":"neutral"}]}/></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Passive data</h2><p>Sensorlaget er uafhængigt af master-skift</p></div><Activity size={20}/></div><InfoList rows={[{label:"RS485",value:controller.rs485_healthy===true?"Healthy":"Afventer",tone:controller.rs485_healthy===true?"ok":"warn"},{label:"Bus traffic",value:bool(state.bus_traffic),tone:state.bus_traffic===true?"ok":"warn"},{label:"Raw mirror",value:"Port 4196"},{label:"Canonical state",value:state.available===true||state.bus_traffic===true?"Aktiv":"Afventer",tone:state.available===true||state.bus_traffic===true?"ok":"warn"},{label:"Master",value:text(controller.active_master)},{label:"Entities ved master-skift",value:"Bevares"}]}/></article>
 <article className="surface panel-card panel-span-2"><div className="pro-card-head compact"><div><h2>Rum fra Home Assistant</h2><p>Værdi, type, prioritet og freshness. Badeværelser bruger separat RH-politik.</p></div><Home size={20}/></div>{roomEntries.length===0?<div className="panel-empty">Ingen friske HA-rum modtaget endnu.</div>:<div className="room-grid">{roomEntries.map(([name,room])=><div className="room-card" key={name}><div><strong>{name}</strong><span>{text(room.room_type,"auto")} · {text(room.priority,"auto")}</span></div><dl><dt>Temperatur</dt><dd>{room.temperature!==undefined?`${text(room.temperature)} °C`:"—"}</dd><dt>RH</dt><dd>{room.humidity!==undefined?`${text(room.humidity)} %`:"—"}</dd><dt>CO₂</dt><dd>{room.co2!==undefined?`${text(room.co2)} ppm`:"—"}</dd><dt>Kontrol</dt><dd>{room.control===false?"Kun visning":"Aktiv"}</dd></dl></div>)}</div>}</article>
 <article className="surface panel-card panel-span-2"><div className="pro-card-head compact"><div><h2>Fallback og sikkerhed</h2><p>Home Assistant kan aldrig omgå lokal arbitration.</p></div><ShieldCheck size={20}/></div><div className="policy-strip"><div><span>HA online</span><strong>Smart inputs → lokal controller</strong></div><div><span>HA offline</span><strong>Local Auto fallback</strong></div><div><span>HCP4 master</span><strong>0 hardware writes · sensorer fortsætter</strong></div></div></article></div></section>}
