import { useCallback, useEffect, useState } from "react";
import { Moon, Save, ShieldCheck, SlidersHorizontal, Wind } from "lucide-react";
import { postJson, requestJson } from "../lib/api";
import "../styles/panels.css";import "../styles/management.css";
type Data=Record<string,unknown>;type Auth={csrf?:string|null;enabled?:boolean;username?:string|null};
function n(v:unknown,f:number){const x=Number(v);return Number.isFinite(x)?x:f}function s(v:unknown,f=""){return v===null||v===undefined?f:String(v)}
export function SettingsPage(){const[controller,setController]=useState<Data>({});const[auth,setAuth]=useState<Auth>({});const[csrf,setCsrf]=useState("");const[form,setForm]=useState<Data>({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[theme,setTheme]=useState(()=>localStorage.getItem("hch5-v2-theme")??"dark");const[collapsed,setCollapsed]=useState(()=>localStorage.getItem("hch5-v2-sidebar")==="1");const[motion,setMotion]=useState(()=>localStorage.getItem("hch5-v2-motion")??"normal");
 const refresh=useCallback(async()=>{const[c,a]=await Promise.all([requestJson<Data>("/api/controller/state"),requestJson<Auth>("/api/auth/status")]);setController(c);setForm(c);setAuth(a);setCsrf(a.csrf??"")},[]);useEffect(()=>{void refresh()},[refresh]);
 const set=(key:string,value:unknown)=>setForm(v=>({...v,[key]:value}));const save=async()=>{if(!csrf)return;setBusy(true);setNotice("Gemmer…");const keys=["local_normal_level","rh_setpoint","rh_hysteresis","co2_setpoint","co2_hysteresis","night_enabled","night_start","night_end","night_level","night_air_quality_max_level","bathroom_rh_setpoint","bathroom_rh_hysteresis","bathroom_max_level","afterheat_setpoint","cooling_enabled","cooling_room_setpoint","cooling_hysteresis","cooling_outdoor_min","cooling_min_delta","cooling_level","ha_timeout_seconds"] ;const patch:Object=Object.fromEntries(keys.map(k=>[k,form[k]]));try{const next=await postJson<Data>("/api/controller/config",patch as Data,csrf);setController(next);setForm(next);setNotice("Indstillinger gemt.")}catch(e){setNotice(`Fejl: ${e instanceof Error?e.message:"ukendt fejl"}`)}finally{setBusy(false)}};
 const uiSave=()=>{localStorage.setItem("hch5-v2-theme",theme);localStorage.setItem("hch5-v2-sidebar",collapsed?"1":"0");localStorage.setItem("hch5-v2-motion",motion);document.documentElement.dataset.motion=motion;window.dispatchEvent(new Event("hch5-ui-preferences"));setNotice("UI-indstillinger gemt.")};
 return <section className="dashboard-overview page-enter"><header className="overview-heading-row"><div><span className="eyebrow">INDSTILLINGER</span><h1>Controller og brugerflade</h1><p>Én samlet config — ingen parallelle eller skjulte hardwareindstillinger.</p></div></header><div className="panel-grid">
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Brugerflade</h2><p>Tema, sidebar og bevægelse</p></div><Moon size={20}/></div><div className="settings-grid"><label>Tema<select value={theme} onChange={e=>setTheme(e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Sidebar<select value={collapsed?"collapsed":"expanded"} onChange={e=>setCollapsed(e.target.value==="collapsed")}><option value="expanded">Expanded</option><option value="collapsed">Collapsed</option></select></label><label>Animation<select value={motion} onChange={e=>setMotion(e.target.value)}><option value="normal">Normal</option><option value="reduced">Reduced</option></select></label><button className="secondary-action" onClick={uiSave}>Gem UI</button></div></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Natdrift</h2><p>Én resolver — nat og luftkvalitet kæmper ikke</p></div><Wind size={20}/></div><div className="settings-grid"><label className="check-row"><input type="checkbox" checked={form.night_enabled===true} onChange={e=>set("night_enabled",e.target.checked)}/> Natsænkning aktiv</label><label>Start<input type="time" value={s(form.night_start,"22:00")} onChange={e=>set("night_start",e.target.value)}/></label><label>Slut<input type="time" value={s(form.night_end,"06:00")} onChange={e=>set("night_end",e.target.value)}/></label><label>Normal nat-trin<input type="number" min="1" max="6" value={n(form.night_level,2)} onChange={e=>set("night_level",Number(e.target.value))}/></label><label>Maks. ved luftkvalitet<input type="number" min="1" max="6" value={n(form.night_air_quality_max_level,4)} onChange={e=>set("night_air_quality_max_level",Number(e.target.value))}/></label></div></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Badeværelse</h2><p>Separat RH-politik så høj fugt ikke giver ukontrolleret fuld boost</p></div><SlidersHorizontal size={20}/></div><div className="settings-grid"><label>RH start<input type="number" min="35" max="90" step="1" value={n(form.bathroom_rh_setpoint,65)} onChange={e=>set("bathroom_rh_setpoint",Number(e.target.value))}/><span>%</span></label><label>Hysterese<input type="number" min="1" max="20" step="1" value={n(form.bathroom_rh_hysteresis,5)} onChange={e=>set("bathroom_rh_hysteresis",Number(e.target.value))}/><span>%</span></label><label>Maks. trin<input type="number" min="1" max="6" value={n(form.bathroom_max_level,4)} onChange={e=>set("bathroom_max_level",Number(e.target.value))}/></label><p className="settings-help">Rum med room_type=bathroom — eller navne som Badeværelse/Bath/Shower — bruger disse værdier. HA kan senere overskrive pr. rum.</p></div></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Generel luftkvalitet</h2><p>Local/Smart Auto</p></div><Wind size={20}/></div><div className="settings-grid"><label>RH setpunkt<input type="number" min="25" max="80" value={n(form.rh_setpoint,50)} onChange={e=>set("rh_setpoint",Number(e.target.value))}/><span>%</span></label><label>RH hysterese<input type="number" min="1" max="10" value={n(form.rh_hysteresis,3)} onChange={e=>set("rh_hysteresis",Number(e.target.value))}/><span>%</span></label><label>CO₂ setpunkt<input type="number" min="500" max="2000" step="50" value={n(form.co2_setpoint,800)} onChange={e=>set("co2_setpoint",Number(e.target.value))}/><span>ppm</span></label><label>Normaltrin<input type="number" min="1" max="6" value={n(form.local_normal_level,3)} onChange={e=>set("local_normal_level",Number(e.target.value))}/></label></div></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Eftervarme</h2><p>HAC1 regulerer selv ventil/aktuator og frostsikring</p></div><ShieldCheck size={20}/></div><div className="settings-grid"><label>Indblæsnings-setpunkt<input type="number" min="18" max="30" value={n(form.afterheat_setpoint,20)} onChange={e=>set("afterheat_setpoint",Number(e.target.value))}/><span>°C</span></label><p className="settings-help">HCH5 Control sender kun temperatur-setpunkt. Der skrives aldrig direkte til varmefladens aktuator.</p></div></article>
 <article className="surface panel-card"><div className="pro-card-head compact"><div><h2>Sikkerhed og session</h2><p>WebUI-auth</p></div><ShieldCheck size={20}/></div><div className="settings-summary"><span>Bruger<strong>{auth.username??"—"}</strong></span><span>Login<strong>{auth.enabled===false?"Deaktiveret":"Aktiveret"}</strong></span><span>Master<strong>{s(controller.active_master,"—")}</strong></span><span>Writes<strong>{controller.hardware_writes_allowed===true?"Allowed":"Blocked"}</strong></span></div></article>
 </div><div className="settings-savebar"><span>{notice||"Ændringer gemmes først når du trykker Gem controller."}</span><button className="primary-action" disabled={busy||!csrf} onClick={()=>void save()}><Save size={15}/>{busy?"Gemmer…":"Gem controller"}</button></div></section>}
