import { useCallback, useEffect, useState } from "react";
import { Activity, Cpu, HardDrive, MemoryStick, Network, Server, Thermometer, Timer } from "lucide-react";
import { HistoryChart } from "../components/HistoryChart";
import { requestJson } from "../lib/api";
import "../styles/panels.css";
import "../styles/history.css";
import "../styles/system.css";
type Data = Record<string, unknown>;
type Sample = Record<string, number | null>;
const n = (v: unknown) => v == null || v === "" || !Number.isFinite(Number(v)) ? null : Number(v);
const t = (v: unknown) => v == null || v === "" ? "—" : String(v);
const p = (v: unknown) => n(v) == null ? "—" : `${n(v)!.toLocaleString("da-DK", {maximumFractionDigits:1})}%`;
const gb = (v: unknown) => n(v) == null ? "—" : `${(n(v)! / 1073741824).toLocaleString("da-DK", {maximumFractionDigits:1})} GB`;
const traffic = (v: unknown) => n(v) == null ? "—" : n(v)! >= 1073741824 ? gb(v) : `${(n(v)! / 1048576).toLocaleString("da-DK", {maximumFractionDigits:1})} MB`;
function Metric({title,value,detail,amount,tone="blue",Icon}:{title:string;value:string;detail:string;amount?:number|null;tone?:string;Icon:typeof Cpu}) {return <article className={`surface system-metric ${tone}`}><div><span>{title}</span><Icon size={18}/></div><strong>{value}</strong><small>{detail}</small>{amount != null && <i className="system-track"><b style={{width:`${Math.max(0,Math.min(100,amount))}%`}}/></i>}</article>}
function Chart({title,detail,samples,field,color,unit}:{title:string;detail:string;samples:Sample[];field:string;color:"blue"|"orange"|"green";unit:string}){return <article className="surface system-chart"><div className="pro-card-head compact"><div><h2>{title}</h2><p>{detail}</p></div><Activity size={18}/></div><HistoryChart samples={samples} series={[{key:field,label:title,color}]} unit={unit} height={160}/></article>}
export function SystemPage(){
 const [state,setState]=useState<Data>({}); const [samples,setSamples]=useState<Sample[]>([]); const [online,setOnline]=useState(false); const [range,setRange]=useState("24h");
 const refresh=useCallback(async(r:string)=>{const [a,b]=await Promise.allSettled([requestJson<Data>("/state.json",{timeoutMs:4000}),requestJson<{samples:Sample[]}>(`/history.json?range=${r}`,{timeoutMs:6000})]);if(a.status==="fulfilled"){setState(a.value);setOnline(true)}else setOnline(false);if(b.status==="fulfilled")setSamples(Array.isArray(b.value.samples)?b.value.samples:[])},[]);
 useEffect(()=>{void refresh(range);const id=window.setInterval(()=>void refresh(range),30000);return()=>window.clearInterval(id)},[range,refresh]);
 const temp=n(state.pi_cpu_temperature??state.system_cpu_temperature),up=n(state.system_uptime_seconds??state.pi_uptime_seconds);const service=(value:unknown)=>value==="active"?"ok":value==="failed"?"bad":value==="inactive"?"stopped":"unknown";const services=[["Controller / gateway",state.service_gateway_activestate],["WebUI",online?"active":"unknown"],["Admin / update",state.service_admin_activestate],["1-Wire",state.service_onewire_activestate],["SSH",state.service_ssh_activestate]];
 return <section className="dashboard-overview page-enter system-page"><header className="overview-heading-row"><div><span className="eyebrow">SYSTEM · RASPBERRY PI</span><h1>Driftsoverblik</h1><p>Ressourcer, historik og services for HCH5 Control.</p></div><span className={`system-online ${online?"ok":"unknown"}`}>● {online?"System online":"Afventer forbindelse"}</span></header>
 <div className="system-metrics"><Metric title="CPU" value={p(state.system_cpu_usage_percent)} detail={`${t(state.system_cpu_frequency_mhz)} MHz · ${t(state.system_cpu_count)} kerner`} amount={n(state.system_cpu_usage_percent)} Icon={Cpu}/><Metric title="CPU-temperatur" value={temp==null?"—":`${temp.toLocaleString("da-DK")}°C`} detail={temp==null?"Ingen måling":temp>=80?"Kritisk temperatur":temp>=70?"Høj temperatur":"Normal temperatur"} amount={temp} tone={temp!=null&&temp>=80?"red":temp!=null&&temp>=70?"orange":"green"} Icon={Thermometer}/><Metric title="RAM" value={p(state.system_memory_used_percent)} detail={`${gb(state.system_memory_used_bytes)} / ${gb(state.system_memory_total_bytes)}`} amount={n(state.system_memory_used_percent)} Icon={MemoryStick}/><Metric title="Disk · /" value={p(state.system_root_used_percent)} detail={`${t(state.system_root_used_gb)} GB brugt · ${t(state.system_root_free_gb)} GB ledig`} amount={n(state.system_root_used_percent)} tone={(n(state.system_root_used_percent)??0)>=85?"orange":"blue"} Icon={HardDrive}/><Metric title="Uptime" value={up==null?"—":`${Math.floor(up/86400)}d ${Math.floor(up%86400/3600)}t ${Math.floor(up%3600/60)}m`} detail={`Boot ${t(state.system_boot_time)}`} Icon={Timer}/></div>
 <div className="system-heading"><div><span className="eyebrow">RESSOURCER</span><h2>Udvikling over tid</h2></div><div className="pro-segment system-range">{[["1h","1 time"],["6h","6 timer"],["24h","24 timer"]].map(([v,l])=><button key={v} className={range===v?"active":""} onClick={()=>setRange(v)}>{l}</button>)}</div></div>
 <div className="system-charts"><Chart title="CPU-forbrug" detail="Belastning i procent" samples={samples} field="system_cpu_usage_percent" color="blue" unit="%"/><Chart title="CPU-temperatur" detail="Advarsel ved 70°C" samples={samples} field="pi_cpu_temperature" color="orange" unit="°C"/><Chart title="RAM-forbrug" detail="Brugt fysisk hukommelse" samples={samples} field="system_memory_used_percent" color="green" unit="%"/></div>
 <div className="system-lower"><article className="surface system-panel"><div className="pro-card-head compact"><div><h2>Services</h2><p>Aktuel status på Pi’en</p></div><Server size={19}/></div><div className="system-services">{services.map(([name,value])=><div key={String(name)}><i className={service(value)}/><strong>{t(name)}</strong><span className={service(value)}>{value==="active"?"OK":value==="failed"?"Fejl":value==="inactive"?"Stoppet":"Ukendt"}</span></div>)}</div></article>
 <article className="surface system-panel"><div className="pro-card-head compact"><div><h2>Netværk</h2><p>Forbindelse og trafik</p></div><Network size={19}/></div><div className="system-network"><strong>{t(state.network_interface)}</strong><span>{t(state.network_ipv4)}</span></div><div className="system-pairs">{[["Modtaget",traffic(state.network_rx_bytes)],["Sendt",traffic(state.network_tx_bytes)],["Gateway",state.network_gateway],["Link",`${t(state.network_link_speed_mbps)} Mbps`]].map(([k,v])=><div key={String(k)}><span>{t(k)}</span><strong>{t(v)}</strong></div>)}</div></article>
 <article className="surface system-panel"><div className="pro-card-head compact"><div><h2>Systeminformation</h2><p>Hardware og software</p></div><Cpu size={19}/></div><div className="system-pairs">{[["Model",state.pi_model??state.system_model],["Hostname",state.system_hostname],["OS",state.system_os],["Kernel",state.system_kernel],["Arkitektur",state.system_architecture],["Python",state.system_python_version],["HCH5 Control",state.system_hch5_version],["Load 1 / 5 / 15",`${t(state.system_load_1m)} / ${t(state.system_load_5m)} / ${t(state.system_load_15m)}`],["Belastning",n(state.system_load_1m)!=null&&n(state.system_cpu_count)!=null?n(state.system_load_1m)!/n(state.system_cpu_count)!>=1?"Høj":"Normal":"—"]].map(([k,v])=><div key={String(k)}><span>{t(k)}</span><strong>{t(v)}</strong></div>)}</div></article></div></section>
}
