import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { Hch5UnitDiagram, type Hch5UnitDiagramProps } from "./Hch5UnitDiagram";
const baseProps:Hch5UnitDiagramProps={outdoor:4.2,extract:22.1,exhaust:8.4,beforeHeater:18.5,afterHeater:21,room:21.7,frost:7,flowWater:34,returnWater:28,supplyRpm:1180,extractRpm:1120,supplyPercent:42,extractPercent:40,bypassActual:false,bypassRequest:"auto",heating:true,recovery:82};
describe("Hch5UnitDiagram",()=>{
  it("crosses both normal air paths through the counter-flow core centre",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m.match(/L520 262/g)?.length).toBeGreaterThanOrEqual(6);expect(m).toContain('points="420,178 620,178 700,262 620,346 420,346 340,262"');for(const port of ["P1","P2","P3","P4"])expect(m).toContain(`>${port}</text>`);expect(m).toContain("is-recovery");});
  it("cross-fades extract from the core to the bottom channel as the damper on the lower fan opens",()=>{const closed=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} bypassRaw={0}/>);expect(closed).toContain('class="hch-bypass closed" transform="translate(800 386)"');expect(closed).toContain("transform:rotate(90deg)");expect(closed).toContain('class="hch-fog-route route-core" style="opacity:1"');expect(closed).toContain('class="hch-fog-route route-bypass" style="opacity:0"');const open=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} bypassActual bypassRaw={255}/>);expect(open).toContain('class="hch-bypass open" transform="translate(800 386)"');expect(open).toContain("transform:rotate(0deg)");expect(open).toContain('class="hch-fog-route route-core" style="opacity:0"');expect(open).toContain('class="hch-fog-route route-bypass" style="opacity:1"');expect(open).toContain("V364 Q294 388 318 388 H772");expect(open).toContain("bypass-actuator");expect(open).toContain("M1247 205 H884");expect(open).toContain("is-bypass");expect(open).toContain("Ekstern eftervarme · HAC1");});
  it("shows a travelling damper at its reported position with both routes partly visible",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} bypassRaw={100}/>);expect(m).toContain('class="hch-bypass closed moving"');expect(m).toContain("transform:rotate(54.7deg)");expect(m).toMatch(/route-bypass" style="opacity:0\.39/);expect(m).toContain("Bevæger sig…");});
  it("marks HAC1 as locked by the 15 C outdoor summer stop",()=>{const free=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} heating={false}/>);expect(free).not.toContain("Sommerstop");const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} heating={false} afterheatLockout/>);expect(m).toContain("Sommerstop · ude ≥ 15 °C");expect(m).toContain(">Spærret</strong>");});
  it("centres temperature ports on the duct flow line so fog runs through them",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toContain("hch-temp-port");expect(m).toContain('translate(1202 205)');expect(m).toContain('translate(1202 365)');expect(m).toContain('translate(-193 205)');expect(m).toContain('translate(-193 365)');expect(m).toContain("Udeluft");expect(m).toContain("Indblæsning");});
  it("fades the fog out with a mask instead of a hard cutoff", ()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toContain("fogFadeMask");expect(m).toContain("fogFadeGradient");expect(m).toMatch(/<mask id="fogFadeMask" maskUnits="userSpaceOnUse"/);});
  it("runs duct stubs out sideways and shows T2 before external coil",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m.match(/hch-duct-pipe/g)?.length).toBe(4);expect(m.match(/class="hch-duct-rim"[^>]*rx="11"/g)?.length).toBe(4);expect(m).not.toContain('rx="43"');expect(m).toContain("T2 før flade");expect(m).toContain("Kun setpunkt styres");});
  it("matches the real HCH5: outdoor, exhaust and both fans on the right, afterheat on the left",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toMatch(/translate\(1202 205\)"><rect[^]*?Udeluft · T1/);expect(m).toMatch(/translate\(1202 365\)"><rect[^]*?Afkast · T4/);expect(m).toMatch(/translate\(-193 365\)"><rect[^]*?Indblæsning · T2AH/);const fanX=[...m.matchAll(/class="hch-fan running" transform="translate\((\d+) /g)].map(f=>Number(f[1]));expect(fanX).toHaveLength(2);for(const x of fanX)expect(x).toBeGreaterThan(700);expect(m).toContain('transform="translate(57 365)"');});
  it("draws the RS485 Modbus cable to HAC1 and the Raspberry Pi, animated only with bus traffic",()=>{const idle=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(idle).toContain("RS485 · Modbus RTU");expect(idle).toContain("HAC1 styring");expect(idle).toContain("Raspberry Pi");expect(idle).toContain('class="hch-wiring"');expect(idle.match(/hch-signal-wire/g)?.length).toBe(3);const live=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} busActive/>);expect(live).toContain('class="hch-wiring active"');});
  it("stops airflow animation with stopped fans",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} supplyRpm={0} extractRpm={0}/>);expect(m.match(/--flow-speed:0s/g)?.length).toBe(12);});
});
