import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { Hch5UnitDiagram, type Hch5UnitDiagramProps } from "./Hch5UnitDiagram";
const baseProps:Hch5UnitDiagramProps={outdoor:4.2,extract:22.1,exhaust:8.4,beforeHeater:18.5,afterHeater:21,room:21.7,frost:7,flowWater:34,returnWater:28,supplyRpm:1180,extractRpm:1120,supplyPercent:42,extractPercent:40,bypassActual:false,bypassRequest:"auto",heating:true,recovery:82};
describe("Hch5UnitDiagram",()=>{
  it("crosses both normal air paths through exchanger centre",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m.match(/L562 295/g)?.length).toBeGreaterThanOrEqual(6);expect(m).toContain("is-recovery");});
  it("reroutes only supply in bypass and keeps the external coil",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} bypassActual/>);expect(m).toContain("Q756 205 756 178 V143");expect(m).toContain("M-238 205 H336");expect(m).toContain("Ekstern eftervarme · HAC1");expect(m).toContain("is-bypass");});
  it("centres temperature ports on the duct flow line so fog runs through them",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toContain("hch-temp-port");expect(m).toContain('translate(1202 205)');expect(m).toContain('translate(1202 365)');expect(m).toContain('translate(-193 205)');expect(m).toContain('translate(-193 365)');expect(m).toContain("Udeluft");expect(m).toContain("Indblæsning");});
  it("fades the fog out with a mask instead of a hard cutoff", ()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toContain("fogFadeMask");expect(m).toContain("fogFadeGradient");expect(m).toMatch(/<mask id="fogFadeMask" maskUnits="userSpaceOnUse"/);});
  it("runs duct stubs out sideways and shows T2 before external coil",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m.match(/hch-duct-pipe/g)?.length).toBe(4);expect(m.match(/class="hch-duct-rim"[^>]*rx="11"/g)?.length).toBe(4);expect(m).not.toContain('rx="43"');expect(m).toContain("T2 før flade");expect(m).toContain("Kun setpunkt styres");});
  it("matches the real HCH5: outdoor, exhaust and both fans on the right, afterheat on the left",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(m).toMatch(/translate\(1202 205\)"><rect[^]*?Udeluft · T1/);expect(m).toMatch(/translate\(1202 365\)"><rect[^]*?Afkast · T4/);expect(m).toMatch(/translate\(-193 365\)"><rect[^]*?Indblæsning · T2AH/);expect(m.match(/class="hch-fan running" transform="translate\(770 /g)?.length).toBe(2);expect(m).toContain('transform="translate(57 365)"');});
  it("draws the RS485 Modbus cable to HAC1 and the Raspberry Pi, animated only with bus traffic",()=>{const idle=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps}/>);expect(idle).toContain("RS485 · Modbus RTU");expect(idle).toContain("HAC1 styring");expect(idle).toContain("Raspberry Pi");expect(idle).toContain('class="hch-wiring"');expect(idle.match(/hch-signal-wire/g)?.length).toBe(3);const live=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} busActive/>);expect(live).toContain('class="hch-wiring active"');});
  it("stops airflow animation with stopped fans",()=>{const m=renderToStaticMarkup(<Hch5UnitDiagram {...baseProps} supplyRpm={0} extractRpm={0}/>);expect(m.match(/--flow-speed:0s/g)?.length).toBe(8);});
});
